### PR TITLE
Fix marching cubes not meshing voxels with few observations

### LINKED ISSUE #38: Marching cubes skips voxels with low weights
There's a hard-coded minimum weight value which is used to determine if a voxel should be meshed or not. If a small number of scans are used to create the surface reconstruction, the output mesh could be incomplete or empty.

https://github.com/ros-industrial/yak/blob/ac84aa6807bc998c39a107c04e8a05df66432bc9/yak/src/mc/marching_cubes.cpp#L42-L47

Probably the root cause of [this issue in `yak_ros`](https://github.com/ros-industrial/yak_ros/issues/30).

### PR DESCRIPTION
**Pull request by schornakj**
Fixes #38 

Sets the minimum voxel weight to `1` when processing the TSDF volume with marching cubes, which means that if a voxel has been observed at least once it'll get meshed.

### CODE REVIEW

**Comment by schornakj** [comment]
@dave992 This should be totally identical to what you described.

File: yak/src/mc/marching_cubes.cpp [hunk 1]
```diff
@@ -39,7 +39,7 @@ std::vector<Triangle> processCube(const yak::TSDFContainer& grid, int x, int y,
     return 5.0f * float(f);
   };
 
-  const static uint16_t min_weight = 4;
+  const static uint16_t min_weight = 1;
```
Comment (gavanderhoorn) [inline yak/src/mc/marching_cubes.cpp:42]: Suggestion: make this a parameter / configurable.

`4` was an assumption which turned out not to work for all cases, but `1` could also suffer from this (it may actually be good for YAK to 'ignore' certain voxels, as a sort of filter).

Allowing users to configure this will make this possible.

Comment (dave992) [reply yak/src/mc/marching_cubes.cpp:42]: I think making this a parameter makes sense. With higher framerate cameras it actually makes sense to skip voxels with a low number of observations, as those are probably regions that are not of interest to the user. 

I will have a look at making this a parameter that we can set.

Comment (schornakj) [reply yak/src/mc/marching_cubes.cpp:42]: @dave992 Since this primarily affects your application, I'll give you some time to explore alternative solutions rather than rushing to merge this in.

**Comment by dave992** [comment]
I did not have permission to push the changes to PR branch, so I've created a branch on our fork [sam-xl:fix/38-mc-voxel-weight](/sam-xl/yak/tree/fix/38-mc-voxel-weight) which adds the `min_weight` parameter to the `yak::MarchingCubesParameters` struct. This still defaults to a `min_weight = 4` so it does not change behavior for current users.

Should I make a new PR for this?

**Comment by schornakj** [comment]
> Should I make a new PR for this?

Go for it! I'll close this one once we merge yours.
